

INSERT INTO stock_back
SELECT stockid, CONCAT(SUBSTRING(DATE,1,4),".",SUBSTRING(DATE,5,2),".",SUBSTRING(DATE,7,2)) AS DATE  ,  CONCAT(SUBSTRING(TIME,1,2),":",SUBSTRING(TIME,3,2)) AS TIME,NULL,NULL,NULL,CLOSE,NULL,NULL,NULL FROM `stock_temp` WHERE SUBSTRING(TIME,3,2) IN('00','15','30','45')


